package com.coco.balancebubble;

import java.util.Random;

/**
 * 一张图文案，附带它说出口时角色要做的动作。
 *
 * <p>语料和动作写在一起，改文案时顺手就能改动作，不会出现「文案改了动作没跟上」。
 */
public final class PetTalk {

    /** 一句台词。 */
    public static final class Line {
        public final String text;
        public final PetAction action;

        Line(String text, PetAction action) {
            this.text = text;
            this.action = action;
        }
    }

    private static final Line[] LINES = {
            new Line("今天也要加油鸭！", PetAction.BOUNCE),
            new Line("你在忙什么呀？", PetAction.LEAN),
            new Line("摸摸头～", PetAction.DUCK),
            new Line("呜哇！吓到了吗？", PetAction.POP),
            new Line("休息一下吧～", PetAction.SLEEPY),
            new Line("我一直在这里哦。", PetAction.FLOAT),
            new Line("要不要喝口水？", PetAction.LEAN),
            new Line("海浪的声音好好听。", PetAction.SWAY),
            new Line("困了…睡一会儿…", PetAction.SLEEPY),
            new Line("记账记得看看哦！", PetAction.NOD),
            new Line("一起去看海吧？", PetAction.FLOAT),
            new Line("今天过得怎么样？", PetAction.LEAN),
            new Line("诶嘿～", PetAction.BOUNCE),
            new Line("我转一圈给你看！", PetAction.SPIN),
            new Line("别熬太晚啦。", PetAction.SHAKE),
            new Line("有好好吃饭吗？", PetAction.LEAN),
            new Line("我在水面漂着呢～", PetAction.FLOAT),
            new Line("要不要抱一下？", PetAction.STRETCH),
            new Line("嘿嘿，被发现了。", PetAction.POP),
            new Line("今天的花销记了吗？", PetAction.NOD),
            new Line("呜…有点冷。", PetAction.DUCK),
            new Line("慢慢来就好。", PetAction.SWAY),
            new Line("我超喜欢你的！", PetAction.BOUNCE),
            new Line("又见面啦～", PetAction.POP),
            new Line("尾巴摇摇～", PetAction.WAG),
            new Line("挥挥小手～", PetAction.WAVE),
            new Line("水面上有星星呢。", PetAction.FLOAT),
            new Line("我想你啦！", PetAction.BOUNCE),
            new Line("嘘…我在发呆。", PetAction.DUCK),
            new Line("尾巴甩甩甩～", PetAction.WAG),
            new Line("要不要一起发呆？", PetAction.LEAN),
            new Line("今天的风好舒服。", PetAction.SWAY),
            new Line("我学会转圈啦！", PetAction.SPIN),
            new Line("别忘了喝水呀～", PetAction.NOD),
            new Line("钱包还撑得住吗？", PetAction.LEAN),
            new Line("该睡觉了哦。", PetAction.SLEEPY),
            new Line("肚子有点饿了…", PetAction.DUCK),
            new Line("给你一个抱抱！", PetAction.STRETCH),
            new Line("有我在，别怕。", PetAction.FLOAT),
            new Line("今天也辛苦啦。", PetAction.NOD),
            new Line("嘿嘿，我可爱吗？", PetAction.BOUNCE),
            new Line("噗——被抓到啦。", PetAction.POP),
            new Line("海风咸咸的～", PetAction.SWAY),
            new Line("来深呼吸一下？", PetAction.STRETCH),
            new Line("我又长胖了吗…", PetAction.DUCK),
            new Line("看，气泡在飘～", PetAction.FLOAT),
            new Line("点我干嘛呀～", PetAction.POP),
            new Line("一起冲呀！", PetAction.BOUNCE),
            new Line("记账记账！", PetAction.NOD),
            new Line("呜…被无视了。", PetAction.SHAKE),
            new Line("早呀，今天也好好的。", PetAction.BOUNCE),
            new Line("晚安，做个好梦。", PetAction.SLEEPY),
            new Line("早上好呀～", PetAction.WAVE),
            new Line("晚上好，累不累？", PetAction.LEAN),
            new Line("我一直在看着你哦。", PetAction.FLOAT),
            new Line("陪你到很晚也没关系。", PetAction.FLOAT),
            new Line("回来啦，欢迎回来。", PetAction.BOUNCE),
            new Line("出门小心一点哦。", PetAction.WAVE),
            new Line("路上注意安全。", PetAction.NOD),
            new Line("到家了跟我说一声。", PetAction.NOD),
            new Line("记得吃早饭哦。", PetAction.NOD),
            new Line("午饭吃了什么呀？", PetAction.LEAN),
            new Line("晚点要吃点东西。", PetAction.LEAN),
            new Line("眼睛累了就歇歇。", PetAction.SLEEPY),
            new Line("记得站起来走走。", PetAction.STRETCH),
            new Line("肩膀酸不酸呀？", PetAction.STRETCH),
            new Line("深呼吸，放松一下。", PetAction.STRETCH),
            new Line("别一直盯着屏幕。", PetAction.SHAKE),
            new Line("坐久了要动一动。", PetAction.STRETCH),
            new Line("今天睡够了吗？", PetAction.SLEEPY),
            new Line("早点睡，别熬夜。", PetAction.SLEEPY),
            new Line("多喝水才不会干。", PetAction.NOD),
            new Line("天冷了记得加衣。", PetAction.DUCK),
            new Line("别忘了吃维生素。", PetAction.NOD),
            new Line("吃饭别太匆忙呀。", PetAction.LEAN),
            new Line("要不要对一下账？", PetAction.NOD),
            new Line("这笔记账了吗？", PetAction.NOD),
            new Line("记账小助手在这儿！", PetAction.BOUNCE),
            new Line("这个月还剩多少？", PetAction.LEAN),
            new Line("有省下一点点吗？", PetAction.NOD),
            new Line("花之前想一想哦。", PetAction.LEAN),
            new Line("这个月超支了吗？", PetAction.SHAKE),
            new Line("别忘了记一笔。", PetAction.NOD),
            new Line("记账是件好事呀。", PetAction.NOD),
            new Line("钱要花在刀刃上。", PetAction.NOD),
            new Line("海里今天很安静。", PetAction.FLOAT),
            new Line("我想去海边玩。", PetAction.BOUNCE),
            new Line("浪花一朵朵～", PetAction.SWAY),
            new Line("潮水涨起来了。", PetAction.FLOAT),
            new Line("海底有小鱼游过。", PetAction.SWAY),
            new Line("我听见鲸鱼在唱歌。", PetAction.SWAY),
            new Line("贝壳里有风声哦。", PetAction.LEAN),
            new Line("沙滩是软软的。", PetAction.DUCK),
            new Line("月光洒在海面上。", PetAction.FLOAT),
            new Line("雨点打在水面上。", PetAction.SWAY),
            new Line("水面起雾了呢。", PetAction.FLOAT),
            new Line("云影飘过海面。", PetAction.FLOAT),
            new Line("潮汐会带回月亮。", PetAction.FLOAT),
            new Line("我捡到一颗小石子。", PetAction.POP),
            new Line("海鸥飞过去了。", PetAction.LEAN),
            new Line("今天天气真好。", PetAction.SWAY),
            new Line("外面在下雨呢。", PetAction.FLOAT),
            new Line("好像在降温了。", PetAction.DUCK),
            new Line("春天快到了吧？", PetAction.LEAN),
            new Line("夏天好热呀。", PetAction.DUCK),
            new Line("秋天落叶好多。", PetAction.SWAY),
            new Line("冬天要穿厚一点。", PetAction.DUCK),
            new Line("太阳晒得好暖。", PetAction.FLOAT),
            new Line("今晚有星星哦。", PetAction.FLOAT),
            new Line("月亮好圆呀。", PetAction.FLOAT),
            new Line("抱抱我嘛～", PetAction.STRETCH),
            new Line("我的手给你牵～", PetAction.STRETCH),
            new Line("看我一眼好不好？", PetAction.LEAN),
            new Line("嘿嘿嘿～", PetAction.BOUNCE),
            new Line("我要黏着你啦。", PetAction.STRETCH),
            new Line("不许不理我哦。", PetAction.SHAKE),
            new Line("陪我说说话嘛。", PetAction.LEAN),
            new Line("我今天很乖哦。", PetAction.NOD),
            new Line("夸夸我好不好？", PetAction.BOUNCE),
            new Line("我是不是变漂亮了？", PetAction.SPIN),
            new Line("偷偷看你一眼～", PetAction.LEAN),
            new Line("你笑起来真好看。", PetAction.BOUNCE),
            new Line("想拉着你的手。", PetAction.STRETCH),
            new Line("靠一会儿可以吗？", PetAction.STRETCH),
            new Line("我有点想你了。", PetAction.BOUNCE),
            new Line("我给你跳个舞！", PetAction.SPIN),
            new Line("看我蹦得多高！", PetAction.BOUNCE),
            new Line("转个圈圈给你看。", PetAction.SPIN),
            new Line("尾巴打个圈圈～", PetAction.WAG),
            new Line("挥手打招呼！", PetAction.WAVE),
            new Line("蹦蹦跳跳真开心。", PetAction.BOUNCE),
            new Line("我摇摆一下～", PetAction.SWAY),
            new Line("伸个懒腰好舒服。", PetAction.STRETCH),
            new Line("我蹲下来躲一下。", PetAction.DUCK),
            new Line("我要飘起来啦～", PetAction.FLOAT),
            new Line("点头表示同意！", PetAction.NOD),
            new Line("摇摇头，不行哦。", PetAction.SHAKE),
            new Line("歪歪头想想事情。", PetAction.LEAN),
            new Line("扑通一下跳进去！", PetAction.POP),
            new Line("打个小盹儿…", PetAction.SLEEPY),
            new Line("你已经做得很好了。", PetAction.NOD),
            new Line("别灰心，慢慢来。", PetAction.SWAY),
            new Line("今天也很了不起。", PetAction.BOUNCE),
            new Line("我相信你可以的。", PetAction.NOD),
            new Line("累了就休息一下。", PetAction.SLEEPY),
            new Line("一步一步往前就好。", PetAction.NOD),
            new Line("你已经很努力了。", PetAction.NOD),
            new Line("别对自己太严格。", PetAction.SWAY),
            new Line("明天会更好的。", PetAction.BOUNCE),
            new Line("我一直在给你加油！", PetAction.BOUNCE),
            new Line("想吃甜甜的东西。", PetAction.LEAN),
            new Line("冰淇淋好好吃。", PetAction.BOUNCE),
            new Line("你吃了吗？", PetAction.LEAN),
            new Line("我今天吃得很饱～", PetAction.NOD),
            new Line("想喝一杯热牛奶。", PetAction.LEAN),
            new Line("要不要一起吃？", PetAction.LEAN),
            new Line("我闻到饭香啦！", PetAction.POP),
            new Line("甜点和下午茶～", PetAction.BOUNCE),
            new Line("别光顾着工作呀。", PetAction.SHAKE),
            new Line("吃点水果吧？", PetAction.LEAN),
            new Line("有点无聊呢…", PetAction.SLEEPY),
            new Line("我好像被冷落了。", PetAction.DUCK),
            new Line("今天心情一般。", PetAction.SWAY),
            new Line("突然有点感伤。", PetAction.DUCK),
            new Line("我有点小委屈。", PetAction.DUCK),
            new Line("不过没关系啦。", PetAction.SWAY),
            new Line("我马上就开心了。", PetAction.BOUNCE),
            new Line("别看我，会害羞的。", PetAction.DUCK),
            new Line("哼，才没有呢。", PetAction.SHAKE),
            new Line("我生气了哦…假的。", PetAction.POP),
            new Line("时间过得好快。", PetAction.SWAY),
            new Line("又是新的一天啦。", PetAction.BOUNCE),
            new Line("已经这么晚了呀。", PetAction.SLEEPY),
            new Line("周一也要加油。", PetAction.BOUNCE),
            new Line("周末好好休息哦。", PetAction.SLEEPY),
            new Line("夜深了，安静点。", PetAction.SLEEPY),
            new Line("午后的阳光很好。", PetAction.FLOAT),
            new Line("清晨的水面很静。", PetAction.FLOAT),
            new Line("快到饭点了呢。", PetAction.LEAN),
            new Line("今天是几号来着？", PetAction.LEAN),
            new Line("你在发呆吗？", PetAction.LEAN),
            new Line("是不是遇到难题了？", PetAction.LEAN),
            new Line("眉头皱起来了哦。", PetAction.LEAN),
            new Line("需要帮忙吗？", PetAction.LEAN),
            new Line("累了就靠着我吧。", PetAction.STRETCH),
            new Line("不想做的事先放着。", PetAction.SWAY),
            new Line("一切都会过去的。", PetAction.SWAY),
            new Line("一步一步来嘛。", PetAction.SWAY),
            new Line("我在这里陪着你。", PetAction.FLOAT),
            new Line("难过了就抱一下。", PetAction.STRETCH),
            new Line("你最喜欢什么呀？", PetAction.LEAN),
            new Line("给我讲个故事吧。", PetAction.LEAN),
            new Line("你会唱歌吗？", PetAction.SPIN),
            new Line("我们聊聊天吧？", PetAction.LEAN),
            new Line("今天有什么好事？", PetAction.BOUNCE),
            new Line("说点有趣的事嘛。", PetAction.LEAN),
            new Line("我什么都想听。", PetAction.LEAN),
            new Line("我们算是好朋友吧？", PetAction.BOUNCE),
            new Line("以后也一起玩呀。", PetAction.BOUNCE),
            new Line("谢谢你一直陪着我。", PetAction.NOD),
            new Line("我是一只小鲸鱼。", PetAction.FLOAT),
            new Line("我的头发软软的。", PetAction.DUCK),
            new Line("我有很多小秘密。", PetAction.DUCK),
            new Line("我也想变厉害一点。", PetAction.STRETCH),
            new Line("我学东西很快的！", PetAction.SPIN),
            new Line("我记性其实挺好。", PetAction.NOD),
            new Line("我喜欢被人夸。", PetAction.BOUNCE),
            new Line("我也会害羞的。", PetAction.DUCK),
            new Line("我有点小骄傲。", PetAction.BOUNCE),
            new Line("我可不只是可爱。", PetAction.SPIN),
            new Line("记得存个备份哦。", PetAction.NOD),
            new Line("记得提交代码呀。", PetAction.NOD),
            new Line("别忘了回消息。", PetAction.NOD),
            new Line("记得给家里打个电话。", PetAction.NOD),
            new Line("文件记得保存！", PetAction.POP),
            new Line("手机上记得充电。", PetAction.NOD),
            new Line("别把钥匙忘了。", PetAction.NOD),
            new Line("出门记得带伞。", PetAction.NOD),
            new Line("记得看看余额哦。", PetAction.LEAN),
            new Line("记得定时起来动动。", PetAction.STRETCH),
            new Line("夜里要盖好被子。", PetAction.SLEEPY),
            new Line("关灯睡觉吧。", PetAction.SLEEPY),
            new Line("睡前别看手机了。", PetAction.SHAKE),
            new Line("抱抱才睡得着。", PetAction.STRETCH),
            new Line("明天见啦～", PetAction.WAVE),
            new Line("梦里也要开心。", PetAction.SLEEPY),
            new Line("晚安，小笨蛋。", PetAction.SLEEPY),
            new Line("替你关好窗户了。", PetAction.NOD),
            new Line("今晚也会好梦的。", PetAction.SLEEPY),
            new Line("睡吧，我守着你。", PetAction.SLEEPY),
            new Line("咦，你在忙呀。", PetAction.LEAN),
            new Line("呀，被你发现了。", PetAction.POP),
            new Line("哇，好厉害！", PetAction.POP),
            new Line("诶？真的吗？", PetAction.LEAN),
            new Line("噗嗤，忍不住笑。", PetAction.POP),
            new Line("好玩好玩！", PetAction.BOUNCE),
            new Line("再来一次嘛～", PetAction.SPIN),
            new Line("我数到三哦。", PetAction.NOD),
            new Line("一二三，开始！", PetAction.BOUNCE),
            new Line("我准备好了！", PetAction.STRETCH),
            new Line("加加油呀～", PetAction.BOUNCE),
            new Line("我也想出去玩。", PetAction.BOUNCE),
            new Line("带我一起嘛～", PetAction.STRETCH),
            new Line("我们出发吧！", PetAction.BOUNCE),
            new Line("慢慢走就好啦。", PetAction.SWAY),
            new Line("前面有彩虹哦。", PetAction.FLOAT),
            new Line("我看到小鱼了！", PetAction.POP),
            new Line("水面闪亮亮的。", PetAction.SWAY),
            new Line("世界真好看呀。", PetAction.FLOAT),
            new Line("明天也要好好的。", PetAction.NOD),
    };

    private static final Random RANDOM = new Random();
    private static int lastIndex = -1;

    private PetTalk() {
    }

    /** 全部台词（测试用）。 */
    public static Line[] all() {
        return LINES.clone();
    }

    public static int size() {
        return LINES.length;
    }

    /** 随机一句，尽量避免和上一句重复。 */
    public static Line random() {
        if (LINES.length == 0) return null;
        int i = RANDOM.nextInt(LINES.length);
        if (LINES.length > 1 && i == lastIndex) {
            i = (i + 1 + RANDOM.nextInt(LINES.length - 2)) % LINES.length;
        }
        lastIndex = i;
        return LINES[i];
    }
}
